version: "3.8"

services:
    # Flask API Backend
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        container_name: home-shopping-api-dev
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=production
            - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
            - SQLALCHEMY_DATABASE_URI=sqlite:///shopping.db
            - HOST=0.0.0.0
            - PORT=5000
            - PYTHONUNBUFFERED=1
        volumes:
            - api-data:/app/instance
        restart: unless-stopped
        networks:
            - home-shopping-dev-network

    # React Frontend
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: home-shopping-dev-frontend
        ports:
            - "3000:80"
        depends_on:
            - api
        restart: unless-stopped
        networks:
            - home-shopping-dev-network

volumes:
    api-data:
        driver: local

networks:
    home-shopping-dev-network:
        driver: bridge
